### ISSUE TITLE
Dump does not contain lookup for EventIDs and InterfaceIDs

### ISSUE THREAD

**Issue by Powback** [EmulatorNexus/Venice-EBX#1]
This makes logic lookups a little harder. Should resolved hashes be considered?

**Comment by OrfeasZ** [comment]
Yeah I just didn't have the list of resolved hashes at hand when uploading this. I will update it soon to list out all the ones that are.

**Comment by Powback** [comment]
Please also log the ones which aren't resolved yet so that I can resolve them.

**Comment by OrfeasZ** [comment]
Names of all known events and fields were added. I've also attached a list of unknown hashes to this reply.

[unknownEvents.txt](https://github.com/EmulatorNexus/Venice-EBX/files/5504907/unknownEvents.txt)
